export const config = {
  developer: {
    name: "Mario Fransiskus Sitepu",
    titleId: "Full Stack Developer | AI Engineer",
    titleEn: "Full Stack Developer | AI Engineer",
    bioId: "Berfokus pada pengembangan web modern dan eksplorasi teknologi AI untuk membangun produk digital yang cerdas, scalable, dan bermanfaat.",
    bioEn: "Focusing on modern web development and exploring AI technologies to build smart, scalable, and impactful digital products.",
    avatar: "/imgpp.jpg",
  },
  social: {
    github: "MarioSitepu",
    email: "stinart123@gmail.com",
    instagram: "mario_stp_",
    locationId: "Lampung Selatan, Lampung",
    locationEn: "South Lampung, Lampung",
  },
  projects: [
    {
      id: 1,
      title: "EduCorner: SahabatMimpi (KKN Project \u2013 Desa Margo Lestari)",
      description: "Platform edukasi interaktif untuk membantu siswa SD-SMA mengenali potensi diri dan cita-cita melalui kuis MBTI berbasis AI.",
      image: "/projects/project-1.webp",
      technologies: ["Next.js", "React", "TypeScript", "PostgreSQL", "Firebase Auth", "Tailwind CSS"],
      github: "#",
      demo: "#",
    },
    {
      id: 2,
      title: "IoT Smart Water Monitoring System (pH & Water Level)",
      description: "Sistem IoT end-to-end untuk memantau kualitas dan ketinggian air secara real-time via Web Dashboard dan WhatsApp Bot.",
      image: "/projects/project-2.webp",
      technologies: ["ESP32", "PHP", "Next.js", "TypeScript", "PostgreSQL", "Azure VM"],
      github: "#",
      demo: "#",
    },
    {
      id: 3,
      title: "Annel Beauty Analytics Website",
      description: "Sistem manajemen penjualan dan analitik untuk bisnis kecantikan multi-toko dengan smart product matching.",
      image: "/projects/project-3.webp",
      technologies: ["Next.js", "Prisma", "PostgreSQL", "Recharts", "Supabase", "Redis"],
      github: "#",
      demo: "#",
    },
    {
      id: 4,
      title: "Survey & Analytics System Untuk Wisudawan",
      description: "Dynamic Form Application berbasis MERN stack dengan dashboard admin dan visualisasi data analitik.",
      image: "/projects/project-4.webp",
      technologies: ["MongoDB", "Express", "React", "Node.js", "Recharts", "Vite"],
      github: "#",
      demo: "#",
    },
    {
      id: 5,
      title: "Website HMIF ITERA",
      description: "Riset dan desain prototipe antarmuka website himpunan yang responsif, mengoptimalkan user flow.",
      image: "/projects/project-5.webp",
      technologies: ["Figma", "UI/UX Research"],
      github: "#",
      demo: "#",
    },
    {
      id: 6,
      title: "Madu Margolestari \u2013 UMKM ECommerce",
      description: "Platform e-commerce modern untuk digitalisasi UMKM madu dengan fitur manajemen produk dan backend REST API.",
      image: "/projects/project-1.webp",
      technologies: ["React", "Node.js", "MongoDB", "Tailwind CSS", "Supabase", "Google OAuth"],
      github: "#",
      demo: "#",
    },
    {
      id: 7,
      title: "YangPentingMakan \u2013 Recipe Sharing",
      description: "Platform berbagi resep makanan praktis bagi mahasiswa dengan fitur upload resep, rating, dan review.",
      image: "/projects/project-2.webp",
      technologies: ["React", "TypeScript", "Node.js", "Express", "MongoDB", "Tailwind CSS"],
      github: "#",
      demo: "#",
    },
    {
      id: 8,
      title: "Website Desa Batang Hari",
      description: "Sistem web berbasis PHP fungsional untuk mengelola data desa, artikel informatif, terhubung melalui cPanel.",
      image: "/projects/project-3.webp",
      technologies: ["PHP", "cPanel", "HTML", "CSS"],
      github: "#",
      demo: "#",
    },
    {
      id: 9,
      title: "Website KMK ITERA (UI/UX)",
      description: "Riset kebutuhan dan desain antarmuka prototipe aplikasi untuk komunitas mahasiswa Katolik.",
      image: "/projects/project-4.webp",
      technologies: ["Figma", "UI/UX Research"],
      github: "#",
      demo: "#",
    },
    {
      id: 10,
      title: "Website KMK ITERA (Frontend)",
      description: "Membangun frontend modern dan mengintegrasikan CMS berbasis Firebase untuk website komunitas.",
      image: "/projects/project-5.webp",
      technologies: ["Next.js", "Tailwind CSS", "Firebase"],
      github: "#",
      demo: "#",
    },
  ],
  skills: [
    { name: "React.js", icon: "react" },
    { name: "Next.js", icon: "nextjs" },
    { name: "Node.js", icon: "nodejs" },
    { name: "TypeScript", icon: "typescript" },
    { name: "JavaScript", icon: "javascript" },
    { name: "TailwindCSS", icon: "tailwind" },
    { name: "MongoDB", icon: "mongodb" },
    { name: "Express", icon: "express" },
    { name: "Git", icon: "git" },
    { name: "AWS", icon: "aws" },
    { name: "Docker", icon: "docker" },
    { name: "Framer Motion", icon: "framer" },
    { name: "Laravel", icon: "laravel" },
    { name: "Supabase", icon: "supabase" },
    { name: "Pyramid", icon: "pyramid" },
    { name: "React Native", icon: "reactnative" },
    { name: "Flutter", icon: "flutter" },
    { name: "Vue.js", icon: "vue" },
  ],
};

